### ISSUE TITLE
CocoaPod

### ISSUE THREAD

**Issue by chy89310** [Blazeice/ScreenAndAudioRecordDemoScreenAndAudioRecordDemo#7]
你好，你的demo正好适合我现在项目的一个需求，非常感谢！
想问一下这个功能有没有打包成插件发布到cocoapod上面？如没有，我打算在你的工作基础上进行一些改进并发布到cocoapod上面，未知可否？

**Comment by Blazeice** [comment]
没事

**Comment by Blazeice** [comment]
阔以……
